### ISSUE TITLE
Nice demo - easy way to integrate into existing app?

### ISSUE THREAD

**Issue by cpalanzo** [michaltakac/meteor-saas-braintree#2]
Great demo app!
However, it's standalone - right?

Is there an "way" to integrate this functionality into an existing Meteor app? 
Or do I have to cut and paste functions and files between this demo and my app?

Sorry - bit of newbie question... but that's what I am.

Thanks!

**Comment by michaltakac** [comment]
@cpalanzo Thank you!

This is just an example of what you can do with Braintree, you're right, it's standalone, but the code is documented pretty well and it will be relatively easy to copy-paste files into your app - it's better because in the process, you'll learn how these methods actually behave and why.

A side note: This app is just reworked version of The Meteor Chef's saas-stripe app and there's cool tutorial explaining lot of things: http://themeteorchef.com/recipes/building-a-saas-with-meteor-stripe-part-1/

Also, I suggest you to have a look at Braintree's developer section, which I used for this integration: https://developers.braintreepayments.com/javascript+node/guides/overview

Feel free to ask any question, I'll try to help with integrating into your app!
My Twitter: https://twitter.com/michaltakac
